# Generated by Django 4.2.5 on 2023-10-04 15:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Products',
        ),
    ]
